### ISSUE TITLE
Cors Missing Allow Origin

### ISSUE THREAD

**Issue by sailendra2017** [savanihd/Laravel-Broadcast-Redis-Socket-io-Tutorial-#9]
Hi,
Can you Resolve following error ?
![image](https://user-images.githubusercontent.com/25950585/104056749-fb12bf00-5216-11eb-9206-dfadf1d5c0f8.png)

**Comment by faraztanveer** [comment]
@sailendra2017  did you find the solution ?

**Comment by sailendra2017** [comment]
@faraztanveer  No i am not getting any solution.

**Comment by sailendra2017** [comment]
@faraztanveer I am using following steps to resolve my issue and its working for me, 

**Steps to resolve "CORS Missing Allow Origin" Error for your Echo Server**

**STEP-1:** Add "transports: ['websocket', 'polling', 'flashsocket'] // Fix CORS error!" Code inside your Echo Server Setup File (public\js\laravel-echo-setup.js) like following code:

**window.Echo = new Echo({
    broadcaster: 'socket.io',
    host: window.location.hostname + ':6001',
    transports: ['websocket', 'polling', 'flashsocket'] // Fix CORS error!
});**

**STEP-2:** Build Your Code Using "npm run dev" command Restart your Laravel Echo Server Using "laravel-echo-server start" command Now check your application, You can't find a CORS error now.
